In [2]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (1.6 MB/9.7 MB, attempt 1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/5e/52/42855bf626868413f761addd574acc6195880ae247a5346477a4361c3acb/pandas-3.0.2-cp313-cp313-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/5e/52/42855bf626868413f761addd574acc6195880ae247a5346477a4361c3acb/pandas-3.0.2-cp313-cp313-win_amd64.whl
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (1.6 MB/9.7 MB, attempt 2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002BAFCFFD450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/5e/52/42855bf626868413f761addd574acc6195880ae247a5346477a4361c3acb/pandas-3.0.2-cp313-cp313-win_amd64.whl
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\asus\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 2.3 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.7 MB 2.0 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.7 MB 2.1 MB/s eta 0:00:04
Resuming download pandas-3.0.2-cp313-cp313-win_amd64.whl (1.6 MB/9.7 MB)
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.7 MB ? eta -:--:--

In [3]:
import pandas as pd
import numpy as np

In [4]:
pip install scikit-learn matplotlib

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\asus\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 505.2 kB/s eta 0:00:15
   -- ------------------------------------- 0.5/8.0 MB 505.2 kB/s eta 0:00:15
   -- ------------------------------------- 0.5/8.0 MB 505.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/8.0 MB 481.2 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/8.0 MB 481.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.0/8.0 MB 475.3 kB/s eta 0:00:15
   ----- ---------------------------------- 1.0/8.0 MB 475.3 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.0 MB 485.6 kB/s eta 0:00:14
   ------ --------------------------------- 1.3/8.0 MB 485.6 kB/s eta 0:00:14
   ------ --------------------------------- 1.3/8.0 MB 485.6 kB/s eta 0:00:14
   ------- -------------------------------- 1.6/8.0 MB 494.6 kB/s eta 0:00:13
   ------- -------------------------------- 1.6/8.0 MB 494.6 kB/s eta 0:00:13
   --------- ------------------------------ 1.8/8.0 MB 497.0 kB/s eta 0:00:13
   --------- ------------------------------ 1.8/8.0 MB 497.0 kB/s eta 0:00:13
   ---------- ----------------------------- 2.1/8.0 MB 511.8 kB/s eta 0:00:12
   ----------- ---------------------------- 2.4/8.0 MB 516.3 kB/s eta 0:00:11
   ----------- ---------------------------- 2.4/8.0 MB 516.3 kB/s eta 0:00:11
   ------------- -------------------------- 2.6/8.0 MB 503.5 kB/s eta 0:00:11
   ------------- -------------------------- 2.6/8.0 MB 503.5 kB/s eta 0:00:11
   ------------- -------------------------- 2.6/8.0 MB 503.5 kB/s eta 0:00:11
   -------------- ------------------------- 2.9/8.0 MB 494.1 kB/s eta 0:00:11
   -------------- ------------------------- 2.9/8.0 MB 494.1 kB/s eta 0:00:11
   -------------- ------------------------- 2.9/8.0 MB 494.1 kB/s eta 0:00:11
   -------------- ------------------------- 2.9/8.0 MB 494.1 kB/s eta 0:00:11
   --------------- ------------------------ 3.1/8.0 MB 465.7 kB/s eta 0:00:11
   --------------- ------------------------ 3.1/8.0 MB 465.7 kB/s eta 0:00:11
   --------------- ------------------------ 3.1/8.0 MB 465.7 kB/s eta 0:00:11
   --------------- ------------------------ 3.1/8.0 MB 465.7 kB/s eta 0:00:11
   ----------------- ---------------------- 3.4/8.0 MB 449.0 kB/s eta 0:00:11
   ----------------- ---------------------- 3.4/8.0 MB 449.0 kB/s eta 0:00:11
   ----------------- ---------------------- 3.4/8.0 MB 449.0 kB/s eta 0:00:11
   ------------------ --------------------- 3.7/8.0 MB 441.0 kB/s eta 0:00:10
   ------------------ --------------------- 3.7/8.0 MB 441.0 kB/s eta 0:00:10
   ------------------ --------------------- 3.7/8.0 MB 441.0 kB/s eta 0:00:10
   ------------------- -------------------- 3.9/8.0 MB 433.2 kB/s eta 0:00:10
   ------------------- -------------------- 3.9/8.0 MB 433.2 kB/s eta 0:00:10
   ------------------- -------------------- 3.9/8.0 MB 433.2 kB/s eta 0:00:10
   ------------------- -------------------- 3.9/8.0 MB 433.2 kB/s eta 0:00:10
   -------------------- ------------------- 4.2/8.0 MB 424.8 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.0 MB 424.8 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.0 MB 424.8 kB/s eta 0:00:09
   ---------------------- ----------------- 4.5/8.0 MB 427.8 kB/s eta 0:00:09
   ---------------------- ----------------- 4.5/8.0 MB 427.8 kB/s eta 0:00:09
   ----------------------- ---------------- 4.7/8.0 MB 428.8 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 428.8 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.0 MB 428.8 kB/s eta 0:00:08
   ------------------------ --------------- 5.0/8.0 MB 429.0 kB/s eta 0:00:08
   ------------------------ --------------- 5.0/8.0 MB 429.0 kB/s eta 0:00:08
   ------------------------ --------------- 5.0/8.0 MB 429.0 kB/s eta 0:00:08
   -------------------------- ------------- 5.2/8.0 MB 427.6 kB/s eta 0:00:07
   -------------------------- ------------- 5.2/8.0 MB 427.6 kB/s eta 0:00:07
   -------------------------- ------------- 5.2/8.0 MB 427.6 kB/s eta 0:00:07
   -------------------------- ------------- 5.2/8.0 MB 427.6 kB/s eta 0:00:07
   --------------------------- ------------ 5.5/8.0 MB 421.5 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 421.5 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.0 MB 421.5 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.0 MB 417.2 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.0 MB 417.2 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.0 MB 417.2 kB/s eta 0:00:06
   ------------------------------ --------- 6.0/8.0 MB 417.5 kB/s eta 0:00:05
   ------------------------------ --------- 6.0/8.0 MB 417.5 kB/s eta 0:00:05
   ------------------------------ --------- 6.0/8.0 MB 417.5 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 414.4 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 414.4 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 414.4 kB/s eta 0:00:05
   ------------------------------- -------- 6.3/8.0 MB 414.4 kB/s eta 0:00:05
   -------------------------------- ------- 6.6/8.0 MB 409.9 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 409.9 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 409.9 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.0 MB 409.9 kB/s eta 0:00:04
   ---------------------------------- ----- 6.8/8.0 MB 406.7 kB/s eta 0:00:03
   ---------------------------------- ----- 6.8/8.0 MB 406.7 kB/s eta 0:00:03
   ----------------------------------- ---- 7.1/8.0 MB 410.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.0 MB 418.4 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.0 MB 418.4 kB/s eta 0:00:02
   -------------------------------------- - 7.6/8.0 MB 423.6 kB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 423.6 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 430.3 kB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 433.1 kB/s  0:00:18
Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.1 MB 923.8 kB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.1 MB 923.8 kB/s eta 0:00:08
   ----- ---------------------------------- 1.0/8.1 MB 835.0 kB/s eta 0:00:09
   ----- ---------------------------------- 1.0/8.1 MB 835.0 kB/s eta 0:00:09
   ----- ---------------------------------- 1.0/8.1 MB 835.0 kB/s eta 0:00:09
   ------ --------------------------------- 1.3/8.1 MB 687.2 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.1 MB 687.2 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.1 MB 669.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.1 MB 669.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.6/8.1 MB 669.8 kB/s eta 0:00:10
   --------- ------------------------------ 1.8/8.1 MB 587.7 kB/s eta 0:00:11
   --------- ------------------------------ 1.8/8.1 MB 587.7 kB/s eta 0:00:11
   ----------- ---------------------------- 2.4/8.1 MB 652.6 kB/s eta 0:00:09
   ----------- ---------------------------- 2.4/8.1 MB 652.6 kB/s eta 0:00:09
   ------------ --------------------------- 2.6/8.1 MB 653.6 kB/s eta 0:00:09
   -------------- ------------------------- 2.9/8.1 MB 670.1 kB/s eta 0:00:08
   -------------- ------------------------- 2.9/8.1 MB 670.1 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.1 MB 658.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.1 MB 658.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.1/8.1 MB 658.4 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 632.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 632.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 632.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 632.7 kB/s eta 0:00:08
   ---------------- ----------------------- 3.4/8.1 MB 632.7 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------ --------------------- 3.7/8.1 MB 574.9 kB/s eta 0:00:08
   ------------------- -------------------- 3.9/8.1 MB 479.3 kB/s eta 0:00:09
   -------------------- ------------------- 4.2/8.1 MB 512.4 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.1 MB 512.4 kB/s eta 0:00:08
   -------------------- ------------------- 4.2/8.1 MB 512.4 kB/s eta 0:00:08
   --------------------- ------------------ 4.5/8.1 MB 497.6 kB/s eta 0:00:08
   --------------------- ------------------ 4.5/8.1 MB 497.6 kB/s eta 0:00:08
   ----------------------- ---------------- 4.7/8.1 MB 503.9 kB/s eta 0:00:07
   ----------------------- ---------------- 4.7/8.1 MB 503.9 kB/s eta 0:00:07
   ------------------------ --------------- 5.0/8.1 MB 508.6 kB/s eta 0:00:07
   ------------------------- -------------- 5.2/8.1 MB 519.7 kB/s eta 0:00:06
   ------------------------- -------------- 5.2/8.1 MB 519.7 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.1 MB 527.3 kB/s eta 0:00:06
   --------------------------- ------------ 5.5/8.1 MB 527.3 kB/s eta 0:00:06
   ---------------------------- ----------- 5.8/8.1 MB 533.3 kB/s eta 0:00:05
   ---------------------------- ----------- 5.8/8.1 MB 533.3 kB/s eta 0:00:05
   ----------------------------- ---------- 6.0/8.1 MB 536.4 kB/s eta 0:00:04
   ------------------------------ --------- 6.3/8.1 MB 543.8 kB/s eta 0:00:04
   ------------------------------ --------- 6.3/8.1 MB 543.8 kB/s eta 0:00:04
   -------------------------------- ------- 6.6/8.1 MB 549.2 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.1 MB 549.2 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.1 MB 549.0 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.1 MB 549.0 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.1 MB 549.0 kB/s eta 0:00:03
   ---------------------------------- ----- 7.1/8.1 MB 540.8 kB/s eta 0:00:02
   ---------------------------------- ----- 7.1/8.1 MB 540.8 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 543.5 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 543.5 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 547.4 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 552.8 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 563.6 kB/s  0:00:14
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.3 MB 629.6 kB/s eta 0:00:03
   -------- ------------------------------- 0.5/2.3 MB 629.6 kB/s eta 0:00:03
   ------------- -------------------------- 0.8/2.3 MB 594.1 kB/s eta 0:00:03
   ------------- -------------------------- 0.8/2.3 MB 594.1 kB/s eta 0:00:03
   ------------- -------------------------- 0.8/2.3 MB 594.1 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 603.1 kB/s eta 0:00:02
   ---------------------- ----------------- 1.3/2.3 MB 603.1 kB/s eta 0:00:02
   ---------------------- ----------------- 1.3/2.3 MB 603.1 kB/s eta 0:00:02
   -------------------------- ------------- 1.6/2.3 MB 569.4 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.3 MB 638.1 kB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.3 MB 638.1 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 637.0 kB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 658.5 kB/s  0:00:03
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.2.0-cp313-cp313-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.1 MB 820.1 kB/s eta 0:00:08
   ---- ----------------------------------- 0.8/7.1 MB 863.9 kB/s eta 0:00:08
   ---- ----------------------------------- 0.8/7.1 MB 863.9 kB/s eta 0:00:08
   ----- ---------------------------------- 1.0/7.1 MB 771.3 kB/s eta 0:00:08
   ----- ---------------------------------- 1.0/7.1 MB 771.3 kB/s eta 0:00:08
   ----- ---------------------------------- 1.0/7.1 MB 771.3 kB/s eta 0:00:08
   ------- -------------------------------- 1.3/7.1 MB 579.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.3/7.1 MB 579.8 kB/s eta 0:00:10
   ------- -------------------------------- 1.3/7.1 MB 579.8 kB/s eta 0:00:10
   -------- ------------------------------- 1.6/7.1 MB 567.7 kB/s eta 0:00:10
   -------- ------------------------------- 1.6/7.1 MB 567.7 kB/s eta 0:00:10
   -------- ------------------------------- 1.6/7.1 MB 567.7 kB/s eta 0:00:10
   ---------- ----------------------------- 1.8/7.1 MB 525.2 kB/s eta 0:00:10
   ---------- ----------------------------- 1.8/7.1 MB 525.2 kB/s eta 0:00:10
   ----------- ---------------------------- 2.1/7.1 MB 528.0 kB/s eta 0:00:10
   ------------- -------------------------- 2.4/7.1 MB 560.6 kB/s eta 0:00:09
   ------------- -------------------------- 2.4/7.1 MB 560.6 kB/s eta 0:00:09
   ---------------- ----------------------- 2.9/7.1 MB 621.4 kB/s eta 0:00:07
   ---------------- ----------------------- 2.9/7.1 MB 621.4 kB/s eta 0:00:07
   ----------------- ---------------------- 3.1/7.1 MB 630.8 kB/s eta 0:00:07
   ----------------- ---------------------- 3.1/7.1 MB 630.8 kB/s eta 0:00:07
   ------------------- -------------------- 3.4/7.1 MB 633.6 kB/s eta 0:00:06
   ------------------- -------------------- 3.4/7.1 MB 633.6 kB/s eta 0:00:06
   -------------------- ------------------- 3.7/7.1 MB 639.9 kB/s eta 0:00:06
   ---------------------- ----------------- 3.9/7.1 MB 648.1 kB/s eta 0:00:05
   ---------------------- ----------------- 3.9/7.1 MB 648.1 kB/s eta 0:00:05
   ------------------------- -------------- 4.5/7.1 MB 677.8 kB/s eta 0:00:04
   ------------------------- -------------- 4.5/7.1 MB 677.8 kB/s eta 0:00:04
   -------------------------- ------------- 4.7/7.1 MB 692.3 kB/s eta 0:00:04
   ---------------------------- ----------- 5.0/7.1 MB 699.0 kB/s eta 0:00:04
   ---------------------------- ----------- 5.0/7.1 MB 699.0 kB/s eta 0:00:04
   ----------------------------- ---------- 5.2/7.1 MB 698.9 kB/s eta 0:00:03
   ----------------------------- ---------- 5.2/7.1 MB 698.9 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   ------------------------------- -------- 5.5/7.1 MB 682.7 kB/s eta 0:00:03
   -------------------------------- ------- 5.8/7.1 MB 564.1 kB/s eta 0:00:03
   -------------------------------- ------- 5.8/7.1 MB 564.1 kB/s eta 0:00:03
   ---------------------------------- ----- 6.0/7.1 MB 563.9 kB/s eta 0:00:02
   ----------------------------------- ---- 6.3/7.1 MB 573.6 kB/s eta 0:00:02
   ------------------------------------- -- 6.6/7.1 MB 587.5 kB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.1 MB 587.5 kB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.1 MB 587.5 kB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.1 MB 587.5 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 572.9 kB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 572.9 kB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 564.3 kB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 559.4 kB/s  0:00:12
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\asus\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
import pandas as pd
import numpy as np

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
print(train.shape)
print(test.shape)

(668, 11)
(223, 10)

In [12]:
#describing the data checking if it need preprocessing
train.describe()

           Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [13]:
test.describe()

           Pclass         Age       SibSp       Parch        Fare
count  223.000000  178.000000  223.000000  223.000000  223.000000
mean     2.345291   29.694775    0.506726    0.304933   32.622551
std      0.850047   15.398053    1.169700    0.634108   61.062047
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   19.250000    0.000000    0.000000    7.879200
50%      3.000000   27.000000    0.000000    0.000000   12.475000
75%      3.000000   37.750000    1.000000    0.000000   30.035400
max      3.000000   71.000000    8.000000    2.000000  512.329200

In [14]:
print(train.columns)
print(test.columns)

Index(['Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked', 'Survived'],
      dtype='str')
Index(['Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked'],
      dtype='str')

In [17]:
print(train['Embarked'].unique())
print(train['Sex'].unique())
# print(train['Ticket'].unique())
# print(train['Cabin'].unique())

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str
<StringArray>
['female', 'male']
Length: 2, dtype: str

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
train.drop(['Ticket', 'Cabin'], axis=1, inplace=True)
test.drop(['Ticket', 'Cabin'], axis=1, inplace=True)

# Handling missing values and encoding categorical variables

for df in [train, test]:
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
    df['Age'].fillna(df['Age'].median(), inplace=True)
    df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)


for df in [train, test]:
    df['Embarked'] = df['Embarked'].astype(str).str.strip()
    df['Embarked'].replace('', np.nan, inplace=True)


train['Sex'].fillna(train['Sex'].mode()[0], inplace=True)
test['Sex'].fillna(test['Sex'].mode()[0], inplace=True)

map_sex = {'male': 0, 'female': 1}
map_embarked = {'S': 0, 'C': 1, 'Q': 2}

# train['Sex'] = train['Sex'].map(map_sex)
# train['Embarked'] = train['Embarked'].map(map_embarked)

for df in [train, test]:
    df['Sex'] = df['Sex'].map(map_sex)
    df['Embarked'] = df['Embarked'].map(map_embarked)

x_train = train[features]
y_train = train['Survived']
x_test = test[features]

print(x_train.isnull().sum())

# scaler = StandardScaler()
# x_train = scaler.fit_transform(x_train)
# x_test = scaler.transform(x_test)

# model = LogisticRegression()
# model.fit(x_train, y_train)
# predictions = model.predict(x_test)

Pclass        0
Sex           0
Age         132
SibSp         0
Parch         0
Fare          0
Embarked      1
dtype: int64

C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].median(), inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:13: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(df['Age'].median(), inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:13: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].replace('', np.nan, inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].replace('', np.nan, inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:21: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train['Sex'].fillna(train['Sex'].mode()[0], inplace=True)
C:\Users\asus\AppData\Local\Temp\ipykernel_16684\2502798499.py:22: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  test['Sex'].fillna(test['Sex'].mode()[0], inplace=True)

In [19]:
print(train['Age'].dtype)
print(train['Age'].isnull().sum())
print(train['Embarked'].unique())

float64
132
[ 0.  1.  2. nan]